# Generated by Django 6.1.1 on 2026-09-13 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('professional_type', models.CharField(choices=[('Carpenter', 'Carpenter'), ('Electrician', 'Electrician'), ('AC Technician', 'AC Technician'), ('Mechanic', 'Mechanic'), ('Plumber', 'Plumber')], max_length=50)),
                ('experience', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('hourly_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile_image', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
