# Generated by Django 6.1.1 on 2026-09-13 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('8-10 AM', '8-10 AM'), ('10-12 PM', '10-12 PM'), ('12-2 PM', '12-2 PM'), ('2-4 PM', '2-4 PM'), ('4-6 PM', '4-6 PM'), ('6-8 PM', '6-8 PM')], max_length=20)),
                ('language', models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Hindi', 'Hindi')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.professional')),
            ],
        ),
    ]
